[package]
name = "cargo-mate"
version = "1.0.22"
edition = "2021"
rust-version = "1.70"
authors = ["Cargo Mate <mate@cargo.do>"]
description = "Rust development companion that enhances cargo with intelligent workflows, state management, performance optimization, and comprehensive project monitoring"
documentation = "https://cargo.do/docs"  
homepage = "https://cargo.do"
repository = "https://github.com/cyber-boost/cargo-mate"
license = "MIT"
readme = "README.md"
keywords = ["cargo", "cli", "build", "development", "optimization"]  
categories = ["development-tools", "command-line-utilities", "configuration", "rust-patterns"]  


# Include only essential files - binaries are downloaded separately
include = [
    "README.md",
    "tools.md",
    "sh/install.sh",
    "sh/wrapper-linux.sh",
    "sh/wrapper-macos.sh",
    "sh/wrapper-windows.bat",
    "sh/wrapper-windows.ps1",
    "cmd.md",
    "src/",
    "Cargo.toml",
]

# Exclude large binary files and build artifacts
exclude = [
    "target/",
    "linux/",
    "macos/",
    "windows/",
    "*.protected",
    "*.exe",
]

[lib]
# This is primarily a binary package, but we include a lib for documentation
name = "cargo_mate"
path = "src/lib.rs"

# Binary targets for the wrapper scripts
[[bin]]
name = "cm"
path = "src/main.rs"

# Metadata for crates.io
[package.metadata]
supported-platforms = ["linux-x86_64", "linux-aarch64", "macos-x86_64", "macos-aarch64", "windows-x86_64"]

[badges]
maintenance = { status = "actively-developed" }  # or "passively-maintained", "as-is", "experimental", "looking-for-maintainer", "deprecated", "none"

[dependencies]
# Minimal dependencies for the installer
anyhow = "1.0"
dirs = "5.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true