[package]
name = "cargo-mate"
version = "1.0.67"
edition = "2021"
rust-version = "1.70"
authors = ["Cargo Mate <mate@cargo.do>"]
description = "Rust development companion that enhances cargo with intelligent workflows, state management, performance optimization, and comprehensive project monitoring. Pure binary package - no C compiler required!"
documentation = "https://cargo.do/docs"  
homepage = "https://cargo.do"
repository = "https://github.com/cyber-boost/cargo-mate"
license = "MIT"
readme = "README.md"
keywords = ["cargo", "cli", "build", "development", "optimization"]  
categories = ["development-tools", "command-line-utilities"]  


# Include only essential files - binaries are downloaded separately
include = [
    "README.md",
    "tools.md",
    "sh/install.sh",
    "sh/pre-install.sh",
    "sh/install-cargo-mate.sh",
    "sh/wrapper-linux.sh",
    "sh/wrapper-macos.sh",
    "sh/wrapper-windows.bat",
    "sh/wrapper-windows.ps1",
    "cmd.md",
    "src/main.rs",
    "Cargo.toml",
]

# Exclude backup files and other non-essential files
exclude = [
    "target/",
    "linux/",
    "macos/",
    "windows/",
    "*.protected",
    "*.exe",
    "*.backup",
]

# Removed library target - this is purely a binary package
# Library functionality removed to eliminate any potential C compiler dependencies

# Binary target for cargo-mate
[[bin]]
name = "cm"
path = "src/main.rs"

# Metadata for crates.io
[package.metadata]
supported-platforms = ["linux-x86_64", "linux-aarch64", "macos-x86_64", "macos-aarch64", "windows-x86_64"]

# Important: This crate has NO system dependencies - no C compiler required!
[package.metadata.system-dependencies]
# Empty section confirms no system dependencies
note = "This crate compiles with zero system dependencies"

[badges]
maintenance = { status = "actively-developed" }  # or "passively-maintained", "as-is", "experimental", "looking-for-maintainer", "deprecated", "none"

[dependencies]
# Minimal dependencies that don't require C compilation
# Using simple error handling to avoid C compiler requirement
# No external crates that require C compilation

[profile.release]
opt-level = 3